### PR TITLE
SC2164: show two possible variants for circumenting the warning

### PR DESCRIPTION
**Pull request by bittorf**
always calling 'exit' is not good in e.g. functions.
the basic idea is at least that the returncode of
cd _is_ evaluated somehow and not ignored.

Reported-by: Garance Alistair Drosehn drosehn@rpi.edu

### CODE REVIEW

**Comment by koalaman** [comment]
Github is being weird and showing "1,230 additions and 574 deletions." with no diff. What's going on? Is the diff against an old version?

**Comment by bittorf** [comment]
i will check...it's against latest HEAD. give me time till tomorrow

**Comment by Arthur2e5** [comment]
bittorf's own master, which is the parent of this commit, is 190 commits behind.

See also https://github.com/bittorf/shellcheck/network.

**Comment by bittorf** [comment]
thanks for reminding me, will update

**Comment by ADTC** [comment]
[Rebase, rebase!](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

**Comment by austin987** [comment]
Ping @bittorf

**Comment by bittorf** [comment]
sorry for holding it up that long, see the new PR: https://github.com/koalaman/shellcheck/pull/822

**Pull request closed without merging**
