### PR TITLE
bats: Add check for useless negation (SC2293)

### LINKED ISSUE #2273: bats: Check for negation that won't fail the test
#### For new checks and feature suggestions
- [x] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

See https://github.com/bats-core/bats-core/issues/462 for more context.
In short: Using negation on a statement (that is not the last) does not trigger a test failure for bats because bash does not trigger the error trap on that. Since this is a deliberate bash decision, we need to educate users about it.

#### Here's a snippet or screenshot that shows the problem:

```bash
#!/usr/bin/env bats

@test "name" {
    ! true # this line should fail the test but doesn't
    true
}
```

#### Here's what shellcheck currently says:

Nothing

#### Here's what I wanted or expected to see:

Warning on the line `! true`: "Negation won't trigger test failure due to bash's design decision not to trigger the error trap on negated statements."

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**
Fixes #2273 

This is the first time I have used Haskell for something useful so please bear with my beginner mistakes. I could not get `./quicktest` to tell me whats wrong with my checks, so some help with this would be appreciated.

Also note that this should remain a draft until [bats 1.5.0 has actually been released](https://github.com/bats-core/bats-core/issues/475).

Please also review the companion wiki pages:

- https://github.com/koalaman/shellcheck/wiki/SC2314
- https://github.com/koalaman/shellcheck/wiki/SC2315

### CODE REVIEW

**Comment by koalaman** [comment]
Looks pretty reasonable! I only have minor comments:
* The message "bats: ! <command> will never fail the test." could be a more actionable "In bats, ! <command> does not cause a test failure. Use 'run ! <command>' instead."
* While the errors are similar, you might as well use two different error codes. That way, when people look at the wiki they'll immediately get the relevant one of the two suggested solutions (ps: sorry about overwriting the wiki page! The contents is still available in the edit history)
* I can shove the dropLast function into ASTLib or something so that the two functions that use it can share it

Do you have any idea about the false positive rate, such as whether `! cmd; [ $? -eq 0 ]` is a common idiom?

I also see that the Ubuntu version is a relatively old 1.2.1 where `run ! true` does not cause a failure. Do you have a sense of how long it takes before the new version is widely adopted? (It's probably less than ShellCheck's release cycle)

**Comment by martin-schulze-vireso** [comment]
> The message "bats: ! <command> will never fail the test." could be a more actionable "In bats, ! <command> does not cause a test failure. Use 'run ! <command>' instead."

Okay, I thought I should not duplicate the edit suggestion.

> While the errors are similar, you might as well use two different error codes. That way, when people look at the wiki they'll immediately get the relevant one of the two suggested solutions (ps: sorry about overwriting the wiki page! The contents is still available in the edit history)

Okay, I must admit I tried to be lazy here...

> I can shove the dropLast function into ASTLib or something so that the two functions that use it can share it

I did not know where to put it, so I just let it sit there. I am fine with that.

> Do you have any idea about the false positive rate, such as whether ! cmd; [ $? -eq 0 ] is a common idiom?

I haven't done a survey on the frequency of this mistake, yet. I believe that most people are unaware of the problem since knowing it requires arcane bash knowledge paired with bats internal implementation knowledge. I have seen several instances in the bats self test suite and none of them explicitly checked the exit code.

> I also see that the Ubuntu version is a relatively old 1.2.1 where run ! true does not cause a failure. Do you have a sense of how long it takes before the new version is widely adopted? (It's probably less than ShellCheck's release cycle)

It is very hard to estimate. We have a following routes of "installation": via `git submodule`, docker image, npm, brew, distribution repository. Historically, bats had very sporadic releases which led some people to just pull master in as `git submodule`. We don't have telemetry that could tell us how many people are using which version so we really can't tell. All I can say is: there are people who upgrade to the current release on the day we release it and there are people who will run into errors on master on the day we push them.

**Comment by koalaman** [comment]
`quicktest` keeps breaking with every new major release of cabal, presumably because I'm not sure how it all works. See https://github.com/koalaman/shellcheck/issues/2286 for the workarounds I last verified.

**Comment by martin-schulze-vireso** [comment]
Okay, I did a little survey of all '*.bats' files in all projects that were listed as dependent on bats. These were ~1.5k files with ~90 KLOC. I found only two beginner projects that made this mistake. I added some more, widely used projects like https://github.com/kata-containers/tests
https://github.com/dokku/dokku  https://github.com/dolthub/dolt most of the established projects use bats-assert's `refute` or `! <command> || false`.

**Comment by koalaman** [comment]
Sounds good! I'm happy to merge this at any time.

**Comment by martin-schulze-vireso** [comment]
Okay, I split the error codes into two and updated them to use [SC2314](../wiki/SC2314)/[SC2315](../wiki/SC2315).

**Comment by koalaman** [comment]
Oops, merged too soon and force pushed off. The tests don't pass anymore. Can you have a look?

**Comment by martin-schulze-vireso** [comment]
Where did the tests fail? Do you have a link?

**Comment by koalaman** [comment]
It failed for me when testing locally. Does the latest iteration pass for you?

**Comment by martin-schulze-vireso** [comment]
No, I must admit that I did not run the tests because I had trouble setting up the haskell environment again and decided to rely on  CI, which does not run on PRs it seems?

Anyways, it took me another hour to set up some environment that runs the tests and can confirm they fail. But it is beyond my why. They look correct and my Haskell skill is too weak to debug this.

**Comment by martin-schulze-vireso** [comment]
I worked around that by creating a file with the test code, thereby getting better diagnostics.

**Pull request merged**
