### PR TITLE
Clean up and optimize getSuspiciousRegexWildcard

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by koalaman** [comment]
Thanks for all the PRs!

**Comment by dimo414** [comment]
It looks like this or one of the earlier PRs broke some builds: https://travis-ci.org/github/koalaman/shellcheck/builds/674194723

**Comment by josephcsible** [comment]
@dimo414 Looks like it was actually caused by 64c31d9, as `fromRight` didn't exist in GHC 8.0 or older. If we still want to support versions that old, then just that commit should be reverted.

**Comment by josephcsible** [comment]
#1925

**Pull request merged**
