### PR TITLE
Binary for s390x 

### PR DESCRIPTION
**Pull request by srajmane**
Added s390x support to build binaries.

### CODE REVIEW

**Comment by koalaman** [comment]
The build appears to time out: https://travis-ci.org/github/koalaman/travistest/jobs/662797428

**Comment by srajmane** [comment]
@koalaman Same changes are working on our travis and I am unable to reproduce the timeout issue at my end.
Secondly added some changes to build binary from Dockerfile. Could you please check the changes?

**Comment by srajmane** [comment]
Build is passing for s390x https://travis-ci.org/github/koalaman/shellcheck/jobs/664360022?utm_medium=notification&utm_source=github_status
Currently working on merging branch with master and squashing the commits .

**Comment by srajmane** [comment]
@koalaman Could you please have a look ?

**Comment by ArturKlauser** [comment]
Note that koalaman's run failed in github_deploy, a step that doesn't really run in your PR since PRs don't have access to Travis secrets which are needed for deployment.

Your run:
> 0.00s$ ./.github_deploy
> +shopt -s extglob
> +[[ false != \t\r\u\e ]]
> +echo 'Missing TRAVIS_SECURE_ENV_VARS. Skipping GitHub deployment.'
> **Missing TRAVIS_SECURE_ENV_VARS. Skipping GitHub deployment.**
> +exit 0
> The command "./.github_deploy" exited with 0

Koalaman's run:
> 3.25s$ ./.github_deploy
> +shopt -s extglob
> +install_deps
> +version=2.7.0
> +case "$(uname)" in
> ++uname
> +sudo apt-get update
> Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
> Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [109 kB]
> Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [109 kB]
> Get:4 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main s390x Packages [733 kB]
> Get:5 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main Translation-en [424 kB]
> Get:6 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe s390x Packages [646 kB]
> Get:7 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe Translation-en [330 kB]
> Get:8 http://ports.ubuntu.com/ubuntu-ports xenial-security/main s390x Packages [519 kB]
> Get:9 http://ports.ubuntu.com/ubuntu-ports xenial-security/main Translation-en [316 kB]
> Get:10 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe s390x Packages [382 kB]
> Get:11 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe Translation-en [199 kB]
> Fetched 3768 kB in 1s (2385 kB/s)
> Reading package lists...
> +sudo apt-get install curl
> Reading package lists...
> Building dependency tree...
> Reading state information...
> curl is already the newest version (7.47.0-1ubuntu2.14).
> 0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
> +curl -L https://github.com/github/hub/releases/download/v2.7.0/hub-linux-amd64-2.7.0.tgz
> +tar xvz --strip-components=1 hub-linux-amd64-2.7.0/bin/hub
> ######################################################################## 100.0%hub-linux-amd64-2.7.0/bin/hub
> ######################################################################## 100.0%
> +hub_path=/home/travis/build/koalaman/travistest/bin/hub
> +git show --no-patch --format=format:%B
> +for tag in '$TAGS'
> +hub release create -F description latest
> +/home/travis/build/koalaman/travistest/bin/hub release create -F description latest
> **./.github_deploy: line 24: /home/travis/build/koalaman/travistest/bin/hub: cannot execute binary file: Exec format error**
> +files=()
> +for file in 'deploy/*'
> +[[ deploy/* == *.@(xz|gz|zip) ]]
> +continue
> +hub release edit -F description latest
> +/home/travis/build/koalaman/travistest/bin/hub release edit -F description latest
> **./.github_deploy: line 24: /home/travis/build/koalaman/travistest/bin/hub: cannot execute binary file: Exec format error**
> +exit 1
> The command "./.github_deploy" exited with 1.

It looks like .github_deploy depends on the fact that it is running on an amd64 architecture since it's using precompiled amd64 binaries (hub-linux-**amd64**-$version.tgz):
```
#!/bin/bash
  set -x
  shopt -s extglob
      
  if [[ "$TRAVIS_SECURE_ENV_VARS" != "true" ]]                                  
  then
    echo >&2 "Missing TRAVIS_SECURE_ENV_VARS. Skipping GitHub deployment."      
    exit 0
  fi  
      
  install_deps() {
    version="2.7.0"  # 2.14.1 fails to overwrite duplicates                     
    case "$(uname)" in
      Linux)
        sudo apt-get update
        sudo apt-get install curl                                               
        curl -L "https://github.com/github/hub/releases/download/v$version/hub-linux-amd64-$version.tgz" | tar xvz --strip-components=1 "hub-linux-amd64-$version/bin/hub"
        ;;
      Darwin)
        curl -L "https://github.com/github/hub/releases/download/v$version/hub-darwin-amd64-$version.tgz" | tar xvz --strip-components=1 "hub-darwin-amd64-$version/bin/hub"
        ;;                                                                      
      *)
        echo "Unknown: $(uname)"                                                
        exit 1
        ;;
    esac 
  
    hub_path="$PWD/bin/hub"      
    hub() {
      "$hub_path" "$@"                                                          
    }
  }
  install_deps
...
```

**Comment by srajmane** [comment]
@ArturKlauser  No pre-compile s390x binaries for hub, so added step to install hub from source.

**Comment by srajmane** [comment]
@ArturKlauser Could you please have a look ?

**Comment by ArturKlauser** [comment]
@srajmane: your change looks reasonable to me. But note that I have no special connection to this project, I'm just a contributor like you.

However, it appears your build did not succeed?
https://travis-ci.com/github/linux-on-ibm-z/shellcheck/jobs/317503315

Also, you might want to add the appropriate secrets to your Travis instance so the runs of github_deploy actually exercise your new code to show that it works.
https://travis-ci.org/github/linux-on-ibm-z/shellcheck/jobs/672862867

> $ ./.github_deploy
> +shopt -s extglob
> +[[ false != \t\r\u\e ]]
> +echo 'Missing TRAVIS_SECURE_ENV_VARS. Skipping GitHub deployment.'
> Missing TRAVIS_SECURE_ENV_VARS. Skipping GitHub deployment.
> +exit 0

**Comment by srajmane** [comment]
@koalaman Added hub installation steps for s390x, could you please review it?

**Comment by koalaman** [comment]
I tried picking this back up now that the build uses TravisCI workspaces and no longer rely on having each job upload binaries, but the build times out: https://travis-ci.org/github/koalaman/travistest/jobs/723200524

**Comment by srajmane** [comment]
@koalaman I have updated .travis.yml file and added workspace for s390x. 
Also build is passing for s390x. Please check build log https://travis-ci.org/github/koalaman/shellcheck/jobs/723724044 and review code changes.

**Comment by koalaman** [comment]
I don't think TravisCI's multi-arch support is stable enough for this functionality at this time

**Pull request closed without merging**
