### PR TITLE
Change to aeson (fixes #1085)

### LINKED ISSUE #1085: Could you use aeson instead of json
Consider `aeson` (http://hackage.haskell.org/package/aeson) instead of `json`. `aeson` is de-facto JSON library for Haskell.

I can do a PR if the change is OK.
  
My motivation is that `aeson` is probably better supported in the long run, given its status in the community.

### PR DESCRIPTION
**Pull request by ngzhian**
Adds bytestring as a dependency for putStrLn encoded values.

### CODE REVIEW

**Comment by koalaman** [comment]
I tried building it with my GHC 8.0.2 and aeson 1.2.4.0, but it's missing `Data.Monoid`:

```
src/ShellCheck/Formatter/JSON.hs:57:7: error:
    • Variable not in scope: (<>) :: t13 -> t12 -> t11
    • Perhaps you meant one of these:
        ‘<*’ (imported from Prelude), ‘*>’ (imported from Prelude),
        ‘<#’ (imported from GHC.Exts)
```

Other than that it looks good!

I'm always terrified when changing the dependencies, because it inevitably breaks on either Ubuntu LTS or the latest version of GHC. I'll try it on some various VMs

**Comment by ngzhian** [comment]
I'm on GHC 8.4.2, aeson 1.3.1.0, not sure what how it built before... updated the imports.

**Comment by koalaman** [comment]
Sorry for taking so long, life's getting in the way! Hoping to have this tested across multiple platforms today or tomorrow.

**Comment by ngzhian** [comment]
No rush! Enjoy your weekend :)

**Pull request merged**
