### PR TITLE
Disable smart typography extension for markdown input

### LINKED ISSUE #1392: En dash in front of long options in man page
#### For bugs
- My shellcheck version: 0.5.0

#### Here's a snippet that shows the problem:

```sh
$ man shellcheck | grep '–'
       -a, –check-sourced
       -C[WHEN], –color[=WHEN]
              For TTY output, enable colors always, never or auto.  The default is auto.  –color without an argument
              is equivalent to –color=always.
       -e CODE1[,CODE2...], –exclude=CODE1[,CODE2...]
       -f FORMAT, –format=FORMAT
       -s shell, –shell=shell
       -V, –version
       -x, –external-sources
```

#### Here's what shellcheck currently says:

The long options shown above are prefixed with `–` ([en dash](https://www.fileformat.info/info/unicode/char/2013/index.htm)). If I copy one of those options verbatim it's treated as a file:

```sh
$ shellcheck –check-sourced *.sh 
–check-sourced: –check-sourced: openBinaryFile: does not exist (No such file or directory)
```

#### Here's what I wanted or expected to see:

All the long options should be prefixed with `--` (two hyphens).

### PR DESCRIPTION
**Pull request by ngzhian**
Fixes #1392

### CODE REVIEW

**Comment by koalaman** [comment]
Are all these extra files intended to be there?

**Comment by ngzhian** [comment]
Good call, they are not supposed to be there, I'll on holiday right now and
will get to this when I'm back!

**Comment by koalaman** [comment]
Take your time. I just came back from four weeks in China and Australia ^^

**Comment by ngzhian** [comment]
fixed :)

**Comment by koalaman** [comment]
Nice, thanks!

**Pull request merged**
