### PR TITLE
Fix build with ghc 8.6.1

### PR DESCRIPTION
**Pull request by peti**

### CODE REVIEW

**Comment by peti** [comment]
Ping?

**Comment by koalaman** [comment]
Works everywhere I tried. Dockerhub's `haskell:latest` image isn't 8.6.1 yet but I'll take your word for it ^^

Sorry about the delay, it's been an especially hectic month.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by koalaman** [comment]
I'll see if I can wrap up the things I wanted in the next release and get this out

**Comment by peti** [comment]
openSUSE now distributes the git snapshot v0.5.0-81-ge0e46e9 to unblock progress with ghc-8.6.1 support.

**Pull request merged**
